#!/bin/bash
#
# For every create-withdrawal-data.*.golden, use bitcoin-cli
# "decoderawtransaction" to dump the contents of the constructed
# transaction.
#
# I'm using this to document the changes that Bitcoin Core v0.17 is
# making to the transactions (shorter signatures thanks to
# https://github.com/bitcoin/bitcoin/pull/13666)
#

bitcoind -testnet -daemon -connect=0.0.0.0
# Give bitcoind time to start up
sleep 5



for i in create-withdrawal-data.*.golden; do
    # Find longest line (which will be the transaction hex)
    # Ref: https://stackoverflow.com/a/7213247
    # With minor mod to capture the line's contents instead of length
    MAX=
    while read -r line; do
        if [ ${#line} -gt ${#MAX} ]; then MAX=$line; fi
    done < "$i"
    bitcoin-cli -testnet decoderawtransaction "$MAX" > "${i/%.golden/.decoded}"
done


bitcoin-cli -testnet stop
