#!/usr/bin/env python3

################################################################################################
#
# smart-diff:
#
# Diff two test files ("golden" or expected output vs "out" or actual output),
# where the golden file is interpreted as a regexp.
#
################################################################################################

import argparse
import difflib
import os
import sys

parser = argparse.ArgumentParser()
parser.add_argument('golden_filename')
parser.add_argument('out_filename')
parser.add_argument('-v', '--verbose', action='store_true', help='show all diffs')
args = parser.parse_args()


def plain_diff(golden_filename, out_filename):
    with open(golden_filename, 'r') as golden:
        golden_lines = golden.readlines()
    with open(out_filename, 'r') as out:
        out_lines = out.readlines()

    diff = difflib.unified_diff(golden_lines, out_lines,
                                fromfile=golden_filename,
                                tofile=out_filename)

    diffs = list(diff)
    if diffs:
        if args.verbose:
            for d in diffs: sys.stderr.write(d)
        else:
            sys.stderr.write("Files {} and {} differ\n".format(golden_filename, out_filename))
            sys.stderr.write("To show diffs: {} --verbose {} {}\n".format(sys.argv[0], golden_filename, out_filename))
        return 1

    return 0


sys.exit(plain_diff(args.golden_filename, args.out_filename))
    
